/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2amc;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Migue
 */
public class Comparacion extends javax.swing.JFrame {

    List<Punto> Lista = new ArrayList<Punto>();
    Par Sol = new Par();
    FuerzaBruta FB = new FuerzaBruta();
    DivideVenceras DV = new DivideVenceras();

    /**
     * Creates new form Comparacion
     */
    public Comparacion(int opcion) {
        initComponents();
        switch (opcion) { //En funcion del caso, muestro un determinado boton
            case 1:
                jLabel1.setText("Comparación de Métodos usando distintas tallas");
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                break;
            case 2:
                jLabel1.setText("Estudio del caso Mejor para el método Divide y Venceras");
                jButton1.setVisible(false);
                jButton3.setVisible(false);
                break;
            case 3:
                jLabel1.setText("Estudio del caso Peor para el método Divide y Venceras");
                jButton2.setVisible(false);
                jButton1.setVisible(false);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Par de puntos más cercanos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Comenzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Caso Mejor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Caso Peor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Vamos a comparar cada metodo en funcion de diferentes tallas
        long tiempoFB = 0, tiempoDV = 0; //Variable para recoger los tiempos de los tests
        DefaultCategoryDataset exhaustivo = new DefaultCategoryDataset();
        DefaultCategoryDataset DyV = new DefaultCategoryDataset();
        jTextArea1.setText(null);
        jTextArea1.append("\tTALLA\tExh.\tDyV\n");
        for (int talla = 500; talla <= 10000; talla += 500) {
            for (int i = 1; i < 16; i++) {
                Lista.clear(); // Limpio la lista
                P2AMC.crearLista(Lista, talla);
                Sol = FB.Test(Lista);
                tiempoFB = tiempoFB + Sol.getTiempo();
                Sol = DV.Test(Lista);
                tiempoDV = tiempoDV + Sol.getTiempo();
            }
            jTextArea1.append("\t" + talla + "\t" + tiempoFB / 15 + " ms" + "\t" + tiempoDV / 15 + " ms\n");
            jTextArea1.update(jTextArea1.getGraphics());
            exhaustivo.addValue(tiempoFB / 15, "tiempo practico", Integer.toString(talla));
            exhaustivo.addValue(((talla * talla) / 784) / 1000, "tiempo teorico", Integer.toString(talla));
            DyV.addValue(tiempoDV / 15, "tiempo practico", Integer.toString(talla));
            DyV.addValue(((talla * Math.log10(talla)) / 784) / 1000, "tiempo teorico", Integer.toString(talla));
            tiempoFB = 0;
            tiempoDV = 0;
        }
        JFreeChart chart_exh = ChartFactory.createLineChart("Metodo Exhaustivo",
                "Talla", "Tiempo en ms", exhaustivo, PlotOrientation.VERTICAL,
                true, true, false);
        JFreeChart chart_DyV = ChartFactory.createLineChart("Metodo Divide y Venceras",
                "Talla", "Tiempo en ms", DyV, PlotOrientation.VERTICAL,
                true, true, false);

        ChartFrame frame = new ChartFrame("JFreeChart", chart_exh);
        frame.pack();
        frame.setVisible(true);
        ChartFrame frame2 = new ChartFrame("JFreeChart", chart_DyV);
        frame2.pack();
        frame2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Estudio del caso mejor
        long tiempoDV = 0;
        jTextArea1.setText(null);
        for (int i = 1; i <= 15; i++) {
            Lista.clear();
            P2AMC.MejorPeor(Lista, 100000, 1);
            Sol = DV.Test(Lista);
            jTextArea1.append("\tPrueba: " + i + " tiempo transcurrido: " + Sol.getTiempo() + "ms\n");
            jTextArea1.update(jTextArea1.getGraphics());
            tiempoDV = tiempoDV + Sol.getTiempo();
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Comparacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTextArea1.append("\n\nTIEMPO MEDIO DIVIDE Y VENCERAS (Caso mejor): " + tiempoDV / 15 + " ms");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Estudio del caso peor
        long tiempoDV = 0;
        jTextArea1.setText(null);
        for (int i = 1; i <= 15; i++) {
            Lista.clear();
            P2AMC.MejorPeor(Lista, 100000, 2);
            Sol = DV.Test(Lista);
            jTextArea1.append("\tPrueba: " + i + " tiempo transcurrido: " + Sol.getTiempo() + "ms\n");
            jTextArea1.update(jTextArea1.getGraphics());
            tiempoDV = tiempoDV + Sol.getTiempo();
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Comparacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTextArea1.append("\n\nTIEMPO MEDIO DIVIDE Y VENCERAS (Caso peor): " + tiempoDV / 15 + " ms");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comparacion(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
